/* The tool marks (cinder#46) as A8 masks, generated by firmware/tools/gen_tool_marks.py: the
 * Claude Code mascot as pixel art (4 x 8 px quadrants of its banner glyphs, 72 x 48) and the
 * OpenAI mark (48 x 48) for Codex. Pure data, host-tested. */
#pragma once

#include <stdint.h>

#define TOOL_MARK_H 48   /* tallest mark; the icon box is TOOL_MARK_MAX_W x TOOL_MARK_H */
#define TOOL_MARK_MAX_W 72

/* tool is ember_tool_t (1 claude, 2 codex). Returns the A8 mask (w x h), its colour (0xRRGGBB),
 * or NULL (T3 keeps its pixel icon, unknown tools have none). */
const uint8_t *tool_mark(int tool, uint32_t *rgb, int *w, int *h);
