#!/usr/bin/env python3
"""Build the tool marks as small A8 masks (cinder#46): the Claude Code mascot (pixel art) and
the OpenAI mark (Codex).

    python3 -m venv v && v/bin/pip install svgpathtools pillow
    v/bin/python firmware/tools/gen_tool_marks.py        # rewrites components/bot/tool_marks.c
    v/bin/python firmware/tools/gen_tool_marks.py --png DIR   # also white-on-alpha PNGs (Ember's previews)

Sources (SVGs committed in firmware/tools/icons/, see docs/features.md for licences):
  Claude Code's mascot ("Clawd") is the pixel grid its welcome banner prints with block
              characters (CLAWD below), in Claude Code's own orange rgb(215,119,87) = #D77757
  openai.svg  simple-icons 13.21.0 (CC0), the OpenAI blossom (removed from later simple-icons
              releases at OpenAI's request; the mark itself stays OpenAI's trademark)
Each path is flattened, filled even-odd at 8x and box-filtered to SIZE x SIZE (anti-aliased
alpha). The device recolours the mask at draw time. Output is committed; this runs only when
a mark changes.
"""
import os
import re
import sys

from PIL import Image, ImageChops, ImageDraw
from svgpathtools import parse_path

SIZE = 48
SS = 8
CELL_W, CELL_H = 4, 8
CLAWD = [" \u2590\u259b\u2588\u2588\u2588\u259c\u258c", "\u259d\u259c\u2588\u2588\u2588\u2588\u2588\u259b\u2598",
         "  \u2598\u2598 \u259d\u259d"]
QUAD = {" ": 0b0000, "\u2590": 0b0101, "\u259b": 0b1110, "\u2588": 0b1111, "\u259c": 0b1101, "\u258c": 0b1010,
        "\u259d": 0b0100, "\u2598": 0b1000}
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "components", "bot", "tool_marks.c")
MARKS = [("claude", None), ("codex", "openai.svg")]


def clawd():
    cols = max(len(r) for r in CLAWD) * 2
    w, h = cols * CELL_W, len(CLAWD) * 2 * CELL_H
    im = Image.new("L", (w, h), 0)
    d = ImageDraw.Draw(im)
    for r, row in enumerate(CLAWD):
        for c, ch in enumerate(row):
            bits = QUAD[ch]
            for q in range(4):
                if bits >> (3 - q) & 1:
                    x = (c * 2 + (q & 1)) * CELL_W
                    y = (r * 2 + (q >> 1)) * CELL_H
                    d.rectangle([x, y, x + CELL_W - 1, y + CELL_H - 1], fill=255)
    return im


def mask(svg):
    d = re.search(r'<path d="([^"]+)"', open(svg).read()).group(1)
    path = parse_path(d)
    big = SIZE * SS
    scale = big / 24.0
    acc = Image.new("1", (big, big), 0)
    for sub in path.continuous_subpaths():
        pts = []
        for seg in sub:
            n = max(2, int(seg.length() * scale / 2))
            pts += [seg.point(i / n) for i in range(n)]
        poly = [(p.real * scale, p.imag * scale) for p in pts]
        layer = Image.new("1", (big, big), 0)
        ImageDraw.Draw(layer).polygon(poly, fill=1)
        acc = ImageChops.logical_xor(acc, layer)
    return acc.convert("L").point(lambda v: 255 if v else 0).resize((SIZE, SIZE), Image.BOX)


MARK_W = {"claude": len(max(CLAWD, key=len)) * 2 * CELL_W}


def main():
    lines = [
        "/* Generated by firmware/tools/gen_tool_marks.py; do not edit. A8 masks of the Claude Code",
        " * mascot and the OpenAI mark (sources and licences in docs/features.md). */",
        '#include "tool_marks.h"',
        "",
    ]
    for name, f in MARKS:
        m = clawd() if f is None else mask(os.path.join(HERE, "icons", f))
        data = list(m.get_flattened_data()) if hasattr(m, "get_flattened_data") else list(m.getdata())
        w, h = m.size
        if "--png" in sys.argv:
            png = Image.new("LA", m.size, (255, 0))
            png.putalpha(m)
            png.save(os.path.join(sys.argv[sys.argv.index("--png") + 1], f"knob-mark-{name}.png"))
        lines.append(f"static const uint8_t k_{name}[{w} * {h}] = {{   /* {w} x {h} */")
        for y in range(h):
            lines.append("    " + ",".join(str(v) for v in data[y * w:(y + 1) * w]) + ",")
        lines.append("};")
        lines.append("")
    lines += [
        "const uint8_t *tool_mark(int tool, uint32_t *rgb, int *w, int *h)",
        "{",
        "    switch (tool) {",
        f"    case 1: *rgb = 0xD77757; *w = {MARK_W['claude']}; *h = {SIZE}; return k_claude;   /* Claude Code orange */",
        f"    case 2: *rgb = 0xFFFFFF; *w = {SIZE}; *h = {SIZE}; return k_codex;   /* OpenAI is black/white */",
        "    default: return 0;",
        "    }",
        "}",
        "",
    ]
    open(OUT, "w").write("\n".join(lines))
    print("wrote", OUT)


if __name__ == "__main__":
    sys.exit(main())
