#!/usr/bin/env python3
"""Usage: python3 firmware/tools/gen_face_fonts.py [TTF]  (rewrites main/font_face_36.c and main/font_digits_96.c)
Subset fonts for the weather and music faces (docs/face-design.md "Fonts"): gauge end labels at 36 px and
the big values at 96 px. Montserrat Medium (the weight of LVGL's built-in Montserrat fonts):
Copyright 2011 The Montserrat Project Authors (https://github.com/JulietaUla/Montserrat),
SIL Open Font License 1.1 (main/OFL.txt).
"""
import os
import sys

from PIL import ImageFont

from gen_title_font import c_char, glyph, pack

HERE = os.path.dirname(os.path.abspath(__file__))
FW = os.path.dirname(HERE)
DEFAULT_TTF = os.path.join(FW, "managed_components/lvgl__lvgl/scripts/built_in_font/Montserrat-Medium.ttf")

FONTS = [
    ("font_face_36", 36, " %+-.0123456789:h°−", 40, 7, -3, 2),
    ("font_digits_96", 96, " %+-0123456789:°½−", 107, 19, -8, 5),
]


def build(ttf, name, size, text, line_height, base_line, ul_pos, ul_thick):
    font = ImageFont.truetype(ttf, size, layout_engine=ImageFont.Layout.BASIC)
    chars = sorted(set(text))
    glyphs = [(ch, glyph(font, ch)) for ch in chars]

    bitmap, dscs, index = [], [], 0
    for ch, (adv, w, h, ox, oy, px) in glyphs:
        data = pack(px)
        bitmap.append((ch, data))
        dscs.append((index, adv, w, h, ox, oy))
        index += len(data)
    assert index < (1 << 20) and all(d[1] < (1 << 12) for d in dscs)
    tops = [oy + h for _, (_, w, h, _, oy, _) in glyphs if h]
    bottoms = [oy for _, (_, w, h, _, oy, _) in glyphs if h]
    assert max(tops) <= line_height - base_line and min(bottoms) >= -base_line, name + ": glyphs leave the line box"
    first = ord(chars[0])
    assert ord(chars[-1]) - first < (1 << 16)

    o = ["/* Generated by firmware/tools/gen_face_fonts.py; do not edit. Montserrat Medium %d px, 4 bpp," % size,
         " * glyphs: %s. Copyright 2011 The Montserrat Project Authors" % "".join(chars),
         " * (https://github.com/JulietaUla/Montserrat), SIL Open Font License 1.1 (main/OFL.txt). */",
         '#include "lvgl.h"', "", "static const uint8_t %s_bitmap[] = {" % name]
    for ch, data in bitmap:
        o.append('    /* U+%04X "%s" */' % (ord(ch), c_char(ch)))
        for i in range(0, len(data), 12):
            o.append("    " + ", ".join("0x%02x" % b for b in data[i:i + 12]) + ",")
    o += ["};", "", "static const lv_font_fmt_txt_glyph_dsc_t %s_glyph_dsc[] = {" % name,
          "    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0},"]
    for idx, adv, w, h, ox, oy in dscs:
        o.append("    {.bitmap_index = %d, .adv_w = %d, .box_w = %d, .box_h = %d, .ofs_x = %d, .ofs_y = %d},"
                 % (idx, adv, w, h, ox, oy))
    o += ["};", "", "static const uint16_t %s_unicode_list[] = {" % name,
          "    " + ", ".join("0x%x" % (ord(ch) - first) for ch in chars), "};", "",
          "static const lv_font_fmt_txt_cmap_t %s_cmaps[] = {" % name,
          "    {.range_start = %d, .range_length = %d, .glyph_id_start = 1, .unicode_list = %s_unicode_list,"
          % (first, ord(chars[-1]) - first + 1, name),
          "     .glyph_id_ofs_list = NULL, .list_length = %d, .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY}," % len(chars),
          "};", "",
          "static const lv_font_fmt_txt_dsc_t %s_dsc = {" % name,
          "    .glyph_bitmap = %s_bitmap," % name,
          "    .glyph_dsc = %s_glyph_dsc," % name,
          "    .cmaps = %s_cmaps," % name,
          "    .kern_dsc = NULL,", "    .kern_scale = 0,", "    .cmap_num = 1,", "    .bpp = 4,",
          "    .kern_classes = 0,", "    .bitmap_format = LV_FONT_FMT_TXT_PLAIN,", "};", "",
          "const lv_font_t %s = {" % name,
          "    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,",
          "    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,",
          "    .line_height = %d," % line_height, "    .base_line = %d," % base_line,
          "    .subpx = LV_FONT_SUBPX_NONE,",
          "    .underline_position = %d," % ul_pos, "    .underline_thickness = %d," % ul_thick,
          "    .dsc = &%s_dsc," % name, "};"]
    out = os.path.join(FW, "main", name + ".c")
    with open(out, "w") as f:
        f.write("\n".join(o) + "\n")
    print("%s: %d glyphs, %d bitmap bytes, line_height %d, base_line %d"
          % (os.path.relpath(out, FW), len(chars), index, line_height, base_line))


def main():
    ttf = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_TTF
    for spec in FONTS:
        build(ttf, *spec)


if __name__ == "__main__":
    main()
