#!/usr/bin/env python3
"""Usage: python3 firmware/tools/gen_title_font.py [TTF]  (rewrites main/font_title_bold.c)
Montserrat Bold: Copyright 2011 The Montserrat Project Authors (https://github.com/JulietaUla/Montserrat),
SIL Open Font License 1.1 (main/OFL.txt).
"""
import os
import sys

from PIL import Image, ImageFont

SIZE = 36
LINE_HEIGHT = 40
BASE_LINE = 7
UNDERLINE_POSITION = -3
UNDERLINE_THICKNESS = 2
NAME = "font_title_bold"
TITLES = ["Updating Firmware", "Restarting"]

HERE = os.path.dirname(os.path.abspath(__file__))
FW = os.path.dirname(HERE)
DEFAULT_TTF = os.path.join(FW, "managed_components/lvgl__lvgl/tests/src/test_files/fonts/Montserrat-Bold.ttf")
OUT = os.path.join(FW, "main", NAME + ".c")


def glyph(font, ch):
    adv = round(font.getlength(ch) * 16)
    if ch == " ":
        return adv, 0, 0, 0, 0, []
    mask, (ox, oy) = font.getmask2(ch, mode="L", anchor="ls")
    mask = Image.frombytes("L", mask.size, bytes(mask)).point(lambda v: (v * 15 + 127) // 255)
    x0, y0, x1, y1 = mask.getbbox()
    mask = mask.crop((x0, y0, x1, y1))
    ox, oy = ox + x0, oy + y0
    w, h = mask.size
    px = [mask.getpixel((x, y)) for y in range(h) for x in range(w)]
    return adv, w, h, ox, -(oy + h), px


def pack(px):
    if len(px) % 2:
        px = px + [0]
    return [(px[i] << 4) | px[i + 1] for i in range(0, len(px), 2)]


def c_char(ch):
    return ch.replace("\\", "\\\\").replace('"', '\\"')


def main():
    ttf = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_TTF
    font = ImageFont.truetype(ttf, SIZE, layout_engine=ImageFont.Layout.BASIC)
    chars = sorted(set("".join(TITLES)))
    glyphs = [(ch, glyph(font, ch)) for ch in chars]

    bitmap, dscs, index = [], [], 0
    for ch, (adv, w, h, ox, oy, px) in glyphs:
        data = pack(px)
        bitmap.append((ch, data))
        dscs.append((index, adv, w, h, ox, oy))
        index += len(data)
    assert index < (1 << 20) and all(d[1] < (1 << 12) for d in dscs)

    tops = [oy + h for _, (_, w, h, _, oy, _) in glyphs if h]
    bottoms = [oy for _, (_, w, h, _, oy, _) in glyphs if h]
    assert max(tops) <= LINE_HEIGHT - BASE_LINE and min(bottoms) >= -BASE_LINE, "glyphs leave the line box"
    base_line, line_height = BASE_LINE, LINE_HEIGHT
    first = ord(chars[0])

    o = []
    o.append("/* Generated by firmware/tools/gen_title_font.py; do not edit. Montserrat Bold %d px, 4 bpp,"
             % SIZE)
    o.append(" * glyphs: %s. Copyright 2011 The Montserrat Project Authors" % "".join(chars))
    o.append(" * (https://github.com/JulietaUla/Montserrat), SIL Open Font License 1.1 (main/OFL.txt). */")
    o.append('#include "lvgl.h"')
    o.append("")
    o.append("static const uint8_t glyph_bitmap[] = {")
    for ch, data in bitmap:
        o.append('    /* U+%04X "%s" */' % (ord(ch), c_char(ch)))
        for i in range(0, len(data), 12):
            o.append("    " + ", ".join("0x%02x" % b for b in data[i:i + 12]) + ",")
    o.append("};")
    o.append("")
    o.append("static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {")
    o.append("    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0},")
    for idx, adv, w, h, ox, oy in dscs:
        o.append("    {.bitmap_index = %d, .adv_w = %d, .box_w = %d, .box_h = %d, .ofs_x = %d, .ofs_y = %d},"
                 % (idx, adv, w, h, ox, oy))
    o.append("};")
    o.append("")
    o.append("static const uint16_t unicode_list[] = {")
    o.append("    " + ", ".join("0x%x" % (ord(ch) - first) for ch in chars))
    o.append("};")
    o.append("")
    o.append("static const lv_font_fmt_txt_cmap_t cmaps[] = {")
    o.append("    {.range_start = %d, .range_length = %d, .glyph_id_start = 1, .unicode_list = unicode_list,"
             % (first, ord(chars[-1]) - first + 1))
    o.append("     .glyph_id_ofs_list = NULL, .list_length = %d, .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY}," % len(chars))
    o.append("};")
    o.append("")
    o.append("static const lv_font_fmt_txt_dsc_t font_dsc = {")
    o.append("    .glyph_bitmap = glyph_bitmap,")
    o.append("    .glyph_dsc = glyph_dsc,")
    o.append("    .cmaps = cmaps,")
    o.append("    .kern_dsc = NULL,")
    o.append("    .kern_scale = 0,")
    o.append("    .cmap_num = 1,")
    o.append("    .bpp = 4,")
    o.append("    .kern_classes = 0,")
    o.append("    .bitmap_format = LV_FONT_FMT_TXT_PLAIN,")
    o.append("};")
    o.append("")
    o.append("const lv_font_t %s = {" % NAME)
    o.append("    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,")
    o.append("    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,")
    o.append("    .line_height = %d," % line_height)
    o.append("    .base_line = %d," % base_line)
    o.append("    .subpx = LV_FONT_SUBPX_NONE,")
    o.append("    .underline_position = %d," % UNDERLINE_POSITION)
    o.append("    .underline_thickness = %d," % UNDERLINE_THICKNESS)
    o.append("    .dsc = &font_dsc,")
    o.append("};")
    with open(OUT, "w") as f:
        f.write("\n".join(o) + "\n")
    print("%s: %d glyphs, %d bitmap bytes, line_height %d, base_line %d"
          % (os.path.relpath(OUT, FW), len(chars), index, line_height, base_line))


if __name__ == "__main__":
    main()
